AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  BucketName:
    Type: String
  CodeKey:
    Type: String

Resources:
  SportsbookScraperFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: BucketName
        S3Key:
          Ref: CodeKey
      Handler: build/index.scrapeSportsbookHandler
      Runtime: nodejs12.x
      MemorySize: 512
      Timeout: 900